In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand()

0.3910971995327617

In [16]:
np.random.rand(4)

array([0.34473605, 0.68193222, 0.72289531, 0.0231389 ])

In [17]:
np.random.rand(4,4)

array([[0.68526091, 0.6772189 , 0.17563512, 0.12230969],
       [0.67292248, 0.299677  , 0.63746972, 0.27213596],
       [0.01318061, 0.31077638, 0.27232941, 0.11090347],
       [0.03522242, 0.6317531 , 0.84749129, 0.11829631]])

In [18]:
np.random.randint(1,15)

14

In [20]:
np.random.randint(1,100, size=(10,10))

array([[ 5, 17, 47,  3, 32, 39, 93, 75, 40, 49],
       [49, 38, 15, 34, 45, 92, 24, 29, 22, 43],
       [54, 22, 20, 77, 60, 61, 12, 73,  4, 29],
       [76, 89, 29, 30,  9, 24, 33, 34, 42, 70],
       [97, 75, 56, 34, 34, 60, 95, 28, 81, 49],
       [27, 57,  6, 72, 87, 40, 14, 18, 65, 83],
       [11, 65,  8, 69, 75, 57, 33, 32, 66, 46],
       [21, 87, 27, 31, 56, 99, 27, 23, 25,  8],
       [71, 23, 19, 93, 45,  8, 61, 53, 62, 22],
       [78,  7, 99, 85, 17,  2, 60, 85, 74, 82]])