In [1]:
import numpy as np

In [9]:
array = np.random.randint(1,10, size=(3,2))
array

array([[8, 3],
       [7, 7],
       [3, 1]])

In [4]:
array.shape

(3, 2)

In [10]:
array.reshape(1,6)

array([[8, 3, 7, 7, 3, 1]])

In [11]:
array.reshape(6,1)

array([[8],
       [3],
       [7],
       [7],
       [3],
       [1]])

In [12]:
array.reshape(2,3)

array([[8, 3, 7],
       [7, 3, 1]])

In [13]:
np.reshape(array, (2,3), 'C')

array([[8, 3, 7],
       [7, 3, 1]])

In [14]:
np.reshape(array, (2,3), 'F')

array([[8, 3, 7],
       [7, 3, 1]])

In [15]:
np.reshape(array, (2,3), 'A')

array([[8, 3, 7],
       [7, 3, 1]])