In [1]:
import numpy as np

In [2]:
vector = np.random.randint(1,20,10)
vector

array([ 4, 16, 11,  9, 17, 12,  1, 16,  9,  7])

In [3]:
matriz = vector.reshape(2,5)
matriz

array([[ 4, 16, 11,  9, 17],
       [12,  1, 16,  9,  7]])

In [6]:
matriz.max()

17

In [7]:
matriz.max(0)

array([12, 16, 16,  9, 17])

In [9]:
matriz.max(1)

array([17, 16])

In [10]:
matriz.argmax()

4

In [12]:
matriz.argmax(0)

array([1, 0, 1, 0, 0], dtype=int64)

In [13]:
vector.min()

1

In [14]:
matriz.min(0)

array([ 4,  1, 11,  9,  7])

In [15]:
vector.argmin()

6

In [17]:
matriz.argmin(0)

array([0, 1, 0, 0, 1], dtype=int64)

In [18]:
vector.ptp()

16

In [20]:
matriz.ptp(0)

array([ 8, 15,  5,  0, 10])

In [22]:
np.percentile(matriz, 50)

10.0

In [23]:
np.percentile(matriz, 100)

17.0

In [25]:
matriz.sort()
matriz

array([[ 4,  9, 11, 16, 17],
       [ 1,  7,  9, 12, 16]])

In [28]:
np.median(matriz, 0)

array([ 2.5,  8. , 10. , 14. , 16.5])

In [29]:
np.median(matriz, 1)

array([11.,  9.])

In [30]:
np.std(matriz)

5.035871324805669

In [31]:
np.var(matriz)

25.360000000000003

In [33]:
np.mean(matriz)

10.2

In [36]:
a = np.asarray(([1,2],[3,4]))
b = np.asarray([5,6])

In [39]:
np.concatenate((a,b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [40]:
print(a.ndim)
print(b.ndim)

2
1


In [41]:
b = np.expand_dims(b, axis=0)
b

array([[5, 6]])

In [42]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [44]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])