In [1]:
import numpy as np

In [2]:
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
pares = array[array % 2 == 0]
pares

array([ 0,  2,  4,  6,  8, 10])

In [4]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [5]:
condicion = array > 5
array[condicion]

array([ 6,  7,  8,  9, 10])

In [6]:
# & = and
array[(array > 5) & (array < 9)]

array([6, 7, 8])

In [7]:
# | = or
array[(array > 5) | (array < 9)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
array[array > 5] = 100
array

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100, 100])

In [9]:
array[array == 100]

array([100, 100, 100, 100, 100])

In [10]:
# Array
array = np.arange(1, 16)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
# Multiplos de 3
array[array % 3 == 0]

array([ 3,  6,  9, 12, 15])

In [12]:
# Impares
array[array % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [13]:
multiplos_3 = array[array % 3 == 0]
multiplos_3

array([ 3,  6,  9, 12, 15])

In [14]:
l = list()
for idx in array:
    if idx not in multiplos_3:
        l.append(idx)

print(l)

[1, 2, 4, 5, 7, 8, 10, 11, 13, 14]


In [31]:
[valor for valor in array if valor not in multiplos_3]

[1, 2, 4, 5, 7, 8, 10, 11, 13, 14]