In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [4]:
array = np.arange(1, 11)
array2 = array.copy()
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


## Operaciones

In [5]:
array * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
array + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
1 / array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [8]:
array ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
array + array2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
array * array2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
matriz = array.reshape(2,5)
matriz2 = matriz.copy()

In [14]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
matriz + matriz2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [15]:
matriz * matriz2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [16]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.matmul(matriz, matriz2.T)

array([[ 55, 130],
       [130, 330]])

In [21]:
matriz.dot(matriz2.T)

array([[ 55, 130],
       [130, 330]])

In [24]:
matriz@matriz2.T

array([[ 55, 130],
       [130, 330]])