In [1]:
import numpy as np

lista = [1,2,3,4,5,6,7,8,9]
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
array = np.asarray(lista)
print(array)

[1 2 3 4 5 6 7 8 9]


In [21]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array[0:9:2]

array([1, 3, 5, 7, 9])

In [23]:
matriz[0,2]

3

In [24]:
array[0:3]

array([1, 2, 3])

In [25]:
array[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
array[-3:]

array([7, 8, 9])

In [28]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [34]:
matriz_3d = np.asarray([matriz])
matriz_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [35]:
print(matriz_3d.shape)
print(matriz_3d.ndim)

(1, 3, 3)
3
