In [1]:
import numpy as np

In [6]:
scalar = np.asarray(42)
print(scalar.ndim)
print(scalar)

0
42


In [7]:
vector = np.asarray([42,33,25])
print(vector.ndim)
print(vector)

1
[42 33 25]


In [9]:
matrix = np.asarray([[42,33,25], [41,96,3], [106,55,81]])
print(matrix.ndim)
print(matrix)

2
[[ 42  33  25]
 [ 41  96   3]
 [106  55  81]]


In [11]:
tensor = np.asarray([[[42,33,25], [41,96,3], [106,55,81]]])
print(tensor.ndim)
print(tensor)

3
[[[ 42  33  25]
  [ 41  96   3]
  [106  55  81]]]


## Agregar dimensiones

In [16]:
vector = np.array([42,33,25], ndmin=10)
print(vector.ndim)
print(vector)

10
[[[[[[[[[[42 33 25]]]]]]]]]]


In [19]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand.ndim)
print(expand)

2
[[1 2 3]]


In [22]:
print(vector)
vector_2 = np.squeeze(vector)
print(vector_2)
print(vector_2.ndim)

[[[[[[[[[[42 33 25]]]]]]]]]]
[42 33 25]
1
